/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CncRouteImport } from './routes/cnc'
import { Route as EuRouteImport } from './routes/eu'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as ModelRouteImport } from './routes/model'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ParkRouteImport } from './routes/park'
import { Route as QuoteRouteImport } from './routes/quote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CncRoute = CncRouteImport.update({
  id: '/cnc',
  path: '/cnc',
  getParentRoute: () => rootRouteImport,
} as any)
const EuRoute = EuRouteImport.update({
  id: '/eu',
  path: '/eu',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkRoute = ParkRouteImport.update({
  id: '/park',
  path: '/park',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/cnc': typeof CncRoute
  '/eu': typeof EuRoute
  '/grants': typeof GrantsRoute
  '/model': typeof ModelRoute
  '/orders': typeof OrdersRoute
  '/park': typeof ParkRoute
  '/quote': typeof QuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/cnc': typeof CncRoute
  '/eu': typeof EuRoute
  '/grants': typeof GrantsRoute
  '/model': typeof ModelRoute
  '/orders': typeof OrdersRoute
  '/park': typeof ParkRoute
  '/quote': typeof QuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/cnc': typeof CncRoute
  '/eu': typeof EuRoute
  '/grants': typeof GrantsRoute
  '/model': typeof ModelRoute
  '/orders': typeof OrdersRoute
  '/park': typeof ParkRoute
  '/quote': typeof QuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/cnc'
    | '/eu'
    | '/grants'
    | '/model'
    | '/orders'
    | '/park'
    | '/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/cnc'
    | '/eu'
    | '/grants'
    | '/model'
    | '/orders'
    | '/park'
    | '/quote'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/cnc'
    | '/eu'
    | '/grants'
    | '/model'
    | '/orders'
    | '/park'
    | '/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  CncRoute: typeof CncRoute
  EuRoute: typeof EuRoute
  GrantsRoute: typeof GrantsRoute
  ModelRoute: typeof ModelRoute
  OrdersRoute: typeof OrdersRoute
  ParkRoute: typeof ParkRoute
  QuoteRoute: typeof QuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cnc': {
      id: '/cnc'
      path: '/cnc'
      fullPath: '/cnc'
      preLoaderRoute: typeof CncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eu': {
      id: '/eu'
      path: '/eu'
      fullPath: '/eu'
      preLoaderRoute: typeof EuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/park': {
      id: '/park'
      path: '/park'
      fullPath: '/park'
      preLoaderRoute: typeof ParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  CncRoute: CncRoute,
  EuRoute: EuRoute,
  GrantsRoute: GrantsRoute,
  ModelRoute: ModelRoute,
  OrdersRoute: OrdersRoute,
  ParkRoute: ParkRoute,
  QuoteRoute: QuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
